# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200505_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
