# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-06 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200506_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 16, 48, 15, 540042), verbose_name='添加时间'),
        ),
    ]
